[package]
name = "ascension"
description = '''The online RPG game for two players, based on playing cards
invented by Antony Ngo 
.https://www.youtube.com/watch?v=NwLkOBRf1iM&ab_channel=AnthonyNgo'''
authors = ["Xenia Melnikova", "Igor Galkin galigorrom@gmail.com"]
categories = ["command-line-interface", "game-development", "games"]
keywords = ["gamedev", "tui", "rpg"]
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/autogalkin/Ascension"
license = "MIT"

[[bin]]
name = "ascension"

[dependencies]
clap = { version = "*", features = ["cargo"] }
crossterm = { version = "*" }
ratatui = { version = "*", default-features = false, features = ["crossterm"] }
rand = "*"
anyhow = "*"
const_format = "*"
