[package]
name = "ascension-macro"
version = "0.1.0"
edition = "2021"

[lib]
#name = "ascension-macro"
#path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = { version = "*", features = ["extra-traits"] }
quote = "*"
proc-macro2 = "*"
r3bl_rs_utils = "*"
